---
abstract: 'Easy installation of the GSL shared library'
author:
  - 'Joel A. Berger <joel.a.berger@gmail.com>'
build_requires:
  Alien::Build: '2.21'
  Alien::Build::MM: '2.21'
  Alien::Role::Dino: '0'
  ExtUtils::MakeMaker: '6.52'
  Test2::V0: '0'
  Test::Alien: '0'
  Test::Alien::Diag: '0'
configure_requires:
  Alien::Build: '2.21'
  Alien::Build::MM: '2.21'
  ExtUtils::MakeMaker: '6.52'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-GSL-Alien
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Base: '2.21'
  Alien::Build: '0.25'
resources:
  IRC: irc://irc.perl.org/#native
  bugtracker: https://github.com/hakonhagland/Math-GSL-Alien/issues
  homepage: https://metacpan.org/pod/Math::GSL::Alien
  repository: https://github.com/hakonhagland/Math-GSL-Alien.git
version: '1.02'
x_alienfile:
  generated_by: 'Alien::Build::MM version 2.83'
  requires:
    share:
      Archive::Tar: '0'
      Config: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Mojo::DOM58: '1.00'
      Mozilla::CA: '0'
      Net::SSLeay: '1.49'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
